export const map1 = {
    box_0: {
        width: 15,
        height: 0.1,
        length: 15,
    },
    box_1: {
        width: 2,
        height: 0.1,
        length: 10,
        position_x: -3,
        position_y: 10,
        position_z: -25,
    },
    box_2: {
        width: 2,
        height: 0.1,
        length: 15,
        position_x: -3,
        position_y: 4,
        position_z: -25,
        rotation_x: 9,
    },
    ramp_3: {
        width: 2,
        length: 2,
        position_x: -5,
        position_y: 0.1,
        position_z: -5,
    },
    ramp_4: {
        width: 2,
        length: 2,
        height: 2,
        position_x: -5,
        position_y: 2.1,
        position_z: -9,
    },
    box_5: {
        width: 2,
        height: 4,
        length: 1,
        position_x: -7,
        position_y: 4,
        position_z: -9,
    },
    box_6: {
        width: 2,
        height: 4,
        length: 1,
        position_x: 1,
        position_y: 4,
        position_z: -9,
    },
    box_7: {
        mass: 40,
        position_x: 5,
        position_y: 2,
        position_z: 5,
    },
    cylinder_8: {
        sides: 4,
        radiusBottom: 4,
        height: 0.5,
        position_x: -10,
        position_y: 0.5,
        position_z: 10,
    },
    cylinder_9: {
        radiusTop: 2,
        radiusBottom: 2,
        height: 2,
        mass: 20,
        sides: 16,
        position_x: -3,
        position_y: 12,
        position_z: -30,
        rotation_z: 90,
    },
};
