export default [
    {
        type: 'vehicle',
        position_y: 11,
        rotation_y: -90,
        position_x: -5,
        position_z: 8,
    },
    {
        shape: 'box',
        position_y: 12,
        width: 4,
        height: 0.1,
        length: 2,
        position_x: 2,
    },
    {
        shape: 'box',
        position_y: 11.01,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -3.68,
        rotation_z: 30,
    },
    {
        shape: 'box',
        position_y: 10,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -7.4,
    },
    {
        shape: 'box',
        position_y: 11.01,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -11.1,
        rotation_z: -30,
    },
    {
        shape: 'box',
        position_y: 13.51,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -14.1,
        rotation_z: -50,
    },
    {
        shape: 'box',
        position_y: 18.47,
        width: 4,
        height: 0.1,
        length: 2,
        position_x: -17.36,
        rotation_z: -60,
    },
    {
        shape: 'box',
        position_y: 23.44,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -20.63,
        rotation_z: -50,
    },
    {
        shape: 'box',
        position_y: 26.24,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -23.43,
        rotation_z: -40,
    },
    {
        shape: 'box',
        position_y: 28.19,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -26.81,
        rotation_z: -20,
    },
    {
        shape: 'box',
        position_y: 28.87,
        width: 5,
        height: 0.1,
        length: 5,
        position_x: -33.65,
    },
    {
        shape: 'box',
        position_y: 19,
        width: 4,
        height: 0.1,
        length: 2,
        position_x: 27.73,
        rotation_z: 10,
    },
    {
        shape: 'box',
        position_y: 8.576,
        width: 6,
        height: 0.1,
        length: 6,
        position_x: 10.858,
        position_z: 4,
        rotation_z: -35,
    },
    {
        shape: 'box',
        position_y: 10,
        width: 4,
        height: 4,
        length: 2,
        position_x: 4,
        position_z: 4,
    },
    {
        shape: 'box',
        position_y: 12,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: 4,
        position_z: 8,
    },
    {
        shape: 'box',
        position_y: 11.013,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: 0.318,
        rotation_z: 30,
        position_z: 8,
    },
    {
        shape: 'box',
        position_y: 10,
        width: 3,
        height: 0.1,
        length: 2,
        position_x: -4.35,
        position_z: 8,
    },
    {
        shape: 'box',
        position_y: 19.693,
        width: 4,
        height: 0.1,
        length: 2,
        position_x: 35.65,
    },
    {
        shape: 'box',
        position_y: 19.693,
        width: 2,
        height: 0.1,
        length: 6,
        position_x: 41.64,
        position_z: 4,
    },
    {
        shape: 'sphere',
        position_x: -34.15,
        position_y: 30.14,
        rotation_y: -90,
        type: 'trigger',
        event: 'checkpoint',
    },
    {
        type: 'trigger',
        shape: 'sphere',
        event: 'finish',
        position_x: 41.65,
        position_y: 20.99,
        position_z: 8.54,
        dataSet: 'checkpointCount:1',
    },
    {
        shape: 'sphere',
        type: 'trigger',
        dataSet: 'dynamic,26,20,43',
        position_x: -5,
        position_y: 11,
        position_z: 8,
        size: 2,
        event: 'setCameraMode',
    },
    {
        shape: 'sphere',
        type: 'trigger',
        dataSet: '25,22,18',
        position_x: 4,
        position_y: 13,
        position_z: 8,
        size: 2,
    },
    {
        shape: 'sphere',
        type: 'trigger',
        dataSet: 'chase',
        position_x: 10.01,
        position_y: 9.92,
        position_z: 1.67,
        size: 3,
        event: 'setCameraMode',
    },
];
