export default {
    vehicle_0: {
        position_x: 10,
        position_y: 1,
        position_z: 10,
        rotation_y: 90,
    },
    box_0: {
        width: 6,
        height: 0.1,
        length: 5,
        position_x: 8,
        position_z: 10,
    },
    ramp_1: {
        position_x: 6,
        position_z: 5,
        width: 2,
        height: 1,
        length: 2,
    },
    trigger_2: {
        event: 'setCameraPosition',
        dataSet: '39,13,-6',
        size: 3,
        position_x: 13,
        position_y: 1,
        position_z: 10,
    },
    box_3: {
        mass: 20,
        position_x: -1,
        position_y: -2.06,
        position_z: 10,
        width: 3,
        height: 2,
        length: 3,
    },
    box_4: {
        position_x: -3,
        position_y: -9,
        position_z: 6.9,
        width: 0.5,
        height: 10,
        length: 0.1,
    },
    box_5: {
        position_x: 1,
        position_y: -9,
        position_z: 6.9,
        width: 0.5,
        height: 10,
        length: 0.1,
    },
    box_6: {
        position_x: 1,
        position_y: -9,
        position_z: 13.1,
        width: 0.5,
        height: 10,
        length: 0.1,
    },
    box_7: {
        position_x: -3,
        position_y: -9,
        position_z: 13.1,
        width: 0.5,
        height: 10,
        length: 0.1,
    },
    box_8: {
        position_x: -4.1,
        position_y: -9,
        position_z: 12,
        width: 0.1,
        height: 10,
        length: 0.3,
    },
    box_9: {
        position_x: -4.1,
        position_y: -9,
        position_z: 8,
        width: 0.1,
        height: 10,
        length: 0.3,
    },
    box_10: {
        position_x: 2.1,
        position_y: -9,
        position_z: 12,
        width: 0.1,
        height: 10,
        length: 0.3,
    },
    box_11: {
        position_x: 2.1,
        position_y: -9,
        position_z: 8,
        width: 0.1,
        height: 10,
        length: 0.3,
    },
    box_12: {
        width: 6,
        height: 0.1,
        length: 5,
        position_x: 8,
        position_z: 10,
        position_y: -17,
    },
    box_13: {
        width: 3,
        height: 0.1,
        length: 3,
        position_x: -1,
        position_z: 10,
        position_y: -21,
    },
    box_14: {
        position_x: 2.3,
        position_y: -7,
        position_z: 10,
        width: 0.1,
        height: 7,
        length: 2,
    },
    box_15: {
        width: 6,
        height: 0.1,
        length: 5,
        position_x: 8,
        position_z: 21,
    },
    box_16: {
        width: 2,
        height: 5,
        length: 0.3,
        position_x: 8,
        position_z: 15.5,
        position_y: -1,
        mass: 40,
        lowFriction: true,
        fixedRotation: true,
    },
    box_17: {
        width: 2,
        height: 7,
        length: 0.5,
        position_x: 4,
        position_z: 15.5,
        position_y: -3,
    },
    box_18: {
        width: 2,
        height: 7,
        length: 0.5,
        position_x: 12,
        position_z: 15.5,
        position_y: -3,
    },
    box_19: {
        width: 0.5,
        height: 0.5,
        length: 1,
        position_x: 8,
        position_z: 15.5,
        position_y: -6.5,
        mass: 10,
        lowFriction: true,
        fixedRotation: true,
    },
    box_20: {
        width: 1,
        height: 0.5,
        length: 1.5,
        position_x: 8,
        position_z: 13.5,
        position_y: -7.5,
    },
    box_21: {
        width: 1,
        height: 0.5,
        length: 1,
        position_x: 8,
        position_z: 17,
        position_y: -7.5,
    },
    box_22: {
        width: 1,
        height: 0.5,
        length: 1,
        position_x: 8,
        position_z: 17,
        position_y: -5.5,
    },
    box_23: {
        width: 0.25,
        height: 0.5,
        length: 1,
        position_x: 7.25,
        position_z: 17,
        position_y: -6.5,
    },
    box_24: {
        width: 0.25,
        height: 0.5,
        length: 1,
        position_x: 8.75,
        position_z: 17,
        position_y: -6.5,
    },
    box_25: {
        width: 5,
        height: 0.1,
        length: 4,
        position_x: 9,
        position_z: 9,
        position_y: -8,
    },
    box_26: {
        width: 2,
        height: 3,
        length: 0.1,
        position_x: 8,
        position_z: 15.1,
        position_y: -3,
    },
    box_27: {
        width: 2,
        height: 3,
        length: 0.1,
        position_x: 8,
        position_z: 15.9,
        position_y: -3,
    },
    box_28: {
        width: 0.25,
        height: 0.5,
        length: 1.5,
        position_x: 8.75,
        position_z: 13.5,
        position_y: -6.5,
    },
    box_29: {
        width: 0.25,
        height: 0.5,
        length: 1.5,
        position_x: 7.25,
        position_z: 13.5,
        position_y: -6.5,
    },
    box_30: {
        width: 2.5,
        height: 1,
        length: 0.5,
        position_x: 4.5,
        position_z: 15.5,
        position_y: -11,
    },
    box_31: {
        width: 2.5,
        height: 1,
        length: 0.5,
        position_x: 11.5,
        position_z: 15.5,
        position_y: -11,
    },
    box_32: {
        width: 6,
        height: 2.5,
        length: 0.5,
        position_x: 8,
        position_z: 15.5,
        position_y: -14.5,
    },
    sphere_33: {
        size: 0.5,
        position_x: 8,
        position_z: 14,
        position_y: -6.5,
        mass: 1,
    },
    box_34: {
        width: 1,
        height: 0.5,
        length: 1.5,
        position_x: 8,
        position_y: -5.5,
        position_z: 13.5,
    },
    box_35: {
        width: 0.5,
        height: 0.5,
        length: 1.5,
        position_x: 8,
        position_z: 11.75,
        position_y: -6.5,
        mass: 10,
        fixedRotation: true,
    },
    box_36: {
        width: 2,
        height: 0.1,
        length: 2,
        position_x: 16,
        position_z: 7,
        position_y: -17,
    },
    box_37: {
        width: 4,
        height: 0.1,
        length: 2,
        position_x: 18,
        position_z: 7,
        position_y: -8,
    },
    box_38: {
        width: 2,
        height: 0.1,
        length: 13,
        position_x: 20,
        position_z: 21.75,
        position_y: -10.25,
        rotation_x: 10,
    },
    box_39: {
        width: 2,
        height: 0.1,
        length: 13,
        position_x: 16,
        position_z: 21.6,
        position_y: -14.75,
        rotation_x: -10,
    },
    box_40: {
        width: 4,
        height: 0.1,
        length: 2,
        position_x: 18,
        position_z: 36.35,
        position_y: -12.5,
    },
    box_41: {
        width: 2,
        height: 0.1,
        length: 13,
        position_x: 16,
        position_z: 21.6,
        position_y: -5.76,
        rotation_x: -10,
    },
    box_42: {
        width: 2,
        height: 0.1,
        length: 2,
        position_x: 16,
        position_z: 36.35,
        position_y: -3.5,
    },
    box_43: {
        width: 1,
        height: 1.5,
        length: 0.5,
        position_x: 8,
        position_y: -6.5,
        position_z: 18.5,
    },
    box_44: {
        width: 2,
        height: 0.1,
        length: 2,
        position_x: 4,
        position_z: 36.35,
        position_y: -2,
    },
    box_45: {
        width: 2,
        height: 0.1,
        length: 4.4,
        position_x: 4,
        position_z: 30.2,
        position_y: -1,
        rotation_x: 13.4,
    },
    box_46: {
        width: 4.1,
        height: 0.1,
        length: 2,
        position_x: 10,
        position_z: 36.35,
        position_y: -2.75,
        rotation_z: -10.5,
    },
    box_47: {
        width: 0.1,
        height: 2,
        length: 0.1,
        position_x: 6.1,
        position_z: 15.1,
        position_y: 2,
    },
    box_48: {
        width: 0.1,
        height: 2,
        length: 0.1,
        position_x: 9.9,
        position_z: 15.1,
        position_y: 2,
    },
    box_49: {
        width: 0.1,
        height: 2,
        length: 0.1,
        position_x: 9.9,
        position_z: 15.9,
        position_y: 2,
    },
    box_50: {
        width: 0.1,
        height: 2,
        length: 0.1,
        position_x: 6.1,
        position_z: 15.9,
        position_y: 2,
    },
    trigger_51: {
        event: 'setCameraPosition',
        dataSet: '-13,4,1',
        size: 3,
        position_x: -1,
        position_y: 1,
        position_z: 10,
    },
    box_52: {
        width: 2,
        height: 0.1,
        length: 6,
        position_x: 8,
        position_z: -17,
        position_y: 2,
    },
    trigger_53: {
        event: 'finish',
        dataSet: '',
        size: 1,
        position_x: 8,
        position_y: 3,
        position_z: -21,
    },
    trigger_54: {
        event: 'setCameraPosition',
        dataSet: '-21,-9,8',
        size: 3,
        position_x: -1,
        position_y: -9,
        position_z: 10,
    },
    trigger_55: {
        event: 'setCameraPosition',
        dataSet: '19,-10,-11',
        size: 3,
        position_x: 6,
        position_y: -16,
        position_z: 10,
    },
    trigger_56: {
        event: 'setCameraPosition',
        dataSet: '30,-3,52',
        size: 3,
        position_x: 16,
        position_y: -13,
        position_z: 23,
    },
    trigger_560: {
        event: 'setCameraPosition',
        dataSet: '43,2,0',
        size: 3,
        position_x: 16,
        position_y: -14,
        position_z: 17,
    },
    trigger_57: {
        event: 'setCameraPosition',
        dataSet: '32,8,-11',
        size: 3,
        position_x: 20,
        position_y: -9,
        position_z: 20,
    },
    trigger_58: {
        event: 'setCameraPosition',
        dataSet: '27,7,43',
        size: 3,
        position_x: 16,
        position_y: -4,
        position_z: 26,
    },
    trigger_59: {
        event: 'setCameraPosition',
        dataSet: '8,12,52',
        size: 3,
        position_x: 9,
        position_y: -2,
        position_z: 36,
    },
};
