export default {
    meta: {
        author: '',
        goals: {
            time: 45e3,
            // time: 29e3,
            respawnCount: 0,
        },
    },
    elements: [
        {
            type: 'vehicle',
            position_y: 11.5,
        },
        {
            shape: 'box',
            width: 5,
            length: 5,
            height: 1,
            position_y: 10,
        },
        {
            shape: 'box',
            width: 8,
            length: 6,
            height: 1,
            position_y: -8,
            position_z: 2,
        },
        {
            shape: 'box',
            position_y: -18,
            position_z: -1,
            height: 1,
            width: 10,
            length: 10,
        },
        {
            shape: 'box',
            position_y: -22,
            position_z: 17,
            height: 1,
            width: 10,
            length: 10,
        },
        {
            shape: 'sphere',
            type: 'trigger',
            event: 'checkpoint',
            position_y: -6.5,
            position_z: 2,
        },
        {
            shape: 'box',
            color: '#a59c89',
            height: 0.2,
            width: 16,
            length: 12,
            position_x: 3,
            position_y: -12,
            position_z: 17,
            rotation_x: -30,
        },
        {
            shape: 'box',
            position_x: 8,
            position_y: -23,
            position_z: 17,
            height: 1,
            width: 6,
            length: 4,
        },
        {
            shape: 'box',
            position_x: 14,
            position_y: -24,
            position_z: 17,
            height: 1,
            width: 6,
            length: 4,
        },
        {
            shape: 'sphere',
            type: 'trigger',
            event: 'checkpoint',
            position_x: 8,
            position_y: -21,
            position_z: 17,
            rotation_y: -90,
        },
        {
            shape: 'box',
            position_x: 18,
            position_y: -25,
            position_z: 13,
            height: 1,
            width: 4,
            length: 6,
        },
        {
            shape: 'box',
            position_x: 18,
            position_y: -26,
            position_z: 7,
            height: 1,
            width: 4,
            length: 6,
        },
        {
            shape: 'box',
            position_x: 14,
            position_y: -27,
            position_z: 3,
            height: 1,
            width: 6,
            length: 4,
        },
        {
            shape: 'box',
            position_x: 8,
            position_y: -28,
            position_z: 3,
            height: 1,
            width: 6,
            length: 4,
        },
        {
            shape: 'sphere',
            type: 'trigger',
            event: 'setCameraPosition',
            dataSet: '32,-13,25',
            position_x: 10,
            position_y: -21,
            position_z: 17,
        },
        {
            shape: 'box',
            type: 'trigger',
            dataSet: '-24,-13,20',
            height: 2,
            length: 1,
            width: 6,
            position_x: 0,
            position_y: -20,
            position_z: 14,
        },
        {
            shape: 'sphere',
            type: 'trigger',
            event: 'setCameraPosition',
            dataSet: '32,-13,-8',
            position_x: 18,
            position_y: -24,
            position_z: 9,
            rotation_y: -90,
        },
        {
            shape: 'box',
            position_x: -2,
            position_y: -31,
            position_z: 4,
            height: 1,
            width: 6,
            length: 6,
        },
        {
            shape: 'sphere',
            type: 'trigger',
            event: 'checkpoint',
            position_x: 8,
            position_y: -26,
            position_z: 3,
            rotation_y: 90,
        },
        {
            shape: 'box',
            position_x: -2,
            position_y: -35,
            position_z: 16,
            height: 1,
            width: 6,
            length: 6,
        },
        {
            shape: 'box',
            position_x: -2,
            position_y: -39,
            position_z: 27,
            height: 1,
            width: 6,
            length: 6,
        },
        {
            shape: 'sphere',
            type: 'trigger',
            event: 'setCameraMode',
            dataSet: 'cinematic,-24,25,0',
            position_y: 12,
        },
        {
            shape: 'sphere',
            type: 'trigger',
            event: 'setCameraPosition',
            dataSet: '-2,-20,-10',
            position_x: -2,
            position_y: -29,
            position_z: 4,
        },
        {
            shape: 'sphere',
            type: 'trigger',
            event: 'setCameraPosition',
            dataSet: '-35,-3,1',
            position_x: 0,
            position_y: -6.5,
            position_z: 2,
        },
        {
            shape: 'sphere',
            type: 'trigger',
            event: 'setCameraPosition',
            dataSet: '6,-21,-20',
            position_x: 10,
            position_y: -26,
            position_z: 3,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'finish',
            dataSet: 'checkpointCount:3',
            radius: 1,
            position_x: -2,
            position_y: -37,
            position_z: 27,
        },
    ],
};
