export default [
    {
        type: 'vehicle',
        position_y: 1,
        rotation_y: -1,
    },
    {
        shape: 'box',
        width: 3,
        height: 0.1,
        length: 20.01,
        position_x: 0,
        position_z: -0.02,
        position_y: 0.07,
    },
    {
        type: 'trigger',
        shape: 'sphere',
        event: 'setCameraPosition',
        dataSet: '-6,10,26',
        size: 3,
        position_x: 0,
        position_y: 1,
        position_z: 0,
    },
    {
        type: 'trigger',
        shape: 'sphere',
        event: 'finish',
        dataSet: '',
        size: 1,
        position_x: -31.5,
        position_y: 17.5,
        position_z: -13.5,
    },
    {
        shape: 'slopeTransition',
        type: 'compound',
        segmentWidth: 3,
        position_y: 0,
        position_z: -20.6,
        position_x: -3,
        segmentCount: 43,
        segmentHeight: 0.11,
        segmentLength: 0.3,
        rotation_x: -6,
    },
    {
        shape: 'loop',
        type: 'compound',
        position_z: -41.48,
        rotation_y: -30,
        rotation_x: 0,
        rotation_z: -90,
        position_y: 0.5,
        segmentWidth: 6,
        radius: 5,
        segmentCount: 23,
        position_x: 11.85,
        segmentPositionOffset: -1.19,
    },
    {
        shape: 'box',
        position_y: 26.7,
        position_x: 22.01,
        position_z: -27,
        height: 6,
        length: 15,
        width: 0.1,
    },
    {
        shape: 'loop',
        type: 'compound',
        position_y: 20.4,
        segmentCount: 7,
        segmentLength: 1,
        rotation_y: -90,
        segmentPositionOffset: 0,
        position_z: -18,
        position_x: 13.95,
        segmentWidth: 6,
    },
    {
        shape: 'box',
        position_y: 12.4,
        height: 0.1,
        length: 6,
        width: 15,
        position_x: -2,
        position_z: -18,
    },
    {
        shape: 'loop',
        type: 'compound',
        position_y: 22.4,
        segmentCount: 8,
        segmentPositionOffset: -1,
        rotation_y: 90,
        segmentWidth: 4,
        position_x: -19,
        position_z: -16,
        radius: 5,
    },
    {
        shape: 'loop',
        type: 'compound',
        position_y: 24.16,
        segmentCount: 7,
        segmentPositionOffset: -1,
        rotation_y: -90,
        segmentWidth: 4,
        position_x: -20.59,
        position_z: -2,
        radius: 4,
        rotation_x: 0,
        rotation_z: 0,
    },
    {
        shape: 'box',
        position_y: 16.16,
        height: 0.1,
        length: 3,
        width: 6,
        position_x: -28.6,
        position_z: -2,
    },
    {
        shape: 'box',
        position_y: 16.16,
        height: 0.1,
        length: 6,
        width: 3,
        position_x: -31.6,
        position_z: -11,
    },
    {
        type: 'trigger',
        shape: 'sphere',
        event: 'setCameraMode',
        dataSet: 'chase',
        size: 3,
        position_y: 1,
        position_z: -11.4,
    },
    {
        shape: 'box',
        type: 'trigger',
        position_y: 15.5,
        position_z: -18,
        width: 1,
        length: 6,
        height: 3,
        event: 'setCameraMode',
        dataSet: 'hood',
    },
    {
        shape: 'box',
        type: 'trigger',
        position_y: 18.26,
        position_z: -2,
        width: 1,
        length: 3,
        height: 2,
        position_x: -26.8,
        event: 'setCameraMode',
        dataSet: 'dynamic',
    },
    {
        shape: 'box',
        position_y: 18.26,
        height: 2,
        length: 1,
        width: 3,
        position_x: -31.6,
        position_z: -6,
        type: 'trigger',
        dataSet: '-26,26,13',
    },
];
