export default {
    meta: {
        author: '',
        goals: {
            time: 11e3,
            respawnCount: 0,
        },
    },
    elements: [
        {
            type: 'vehicle',
            position_y: 1,
        },
        {
            shape: 'sphere',
            type: 'trigger',
            event: 'setCameraMode',
            dataSet: 'chase',
            radius: 3,
            position_y: 1,
        },
        {
            shape: 'box',
            width: 10,
            length: 10,
            height: 0.2,
            position_y: -0.1,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'finish',
            dataSet: 'checkpointCount:1',
            radius: 1,
            position_x: 30,
            position_y: 1,
        },
        {
            shape: 'box',
            width: 10,
            length: 20,
            height: 0.2,
            position_y: -0.1,
            position_z: -15,
        },
        {
            shape: 'box',
            width: 20,
            length: 10,
            height: 0.2,
            position_y: -0.1,
            position_x: 15,
        },
        {
            shape: 'box',
            width: 20,
            length: 10,
            height: 0.2,
            position_y: -0.1,
            position_z: -30,
        },
        {
            shape: 'box',
            width: 10,
            length: 20,
            height: 0.2,
            position_y: -0.1,
            position_x: 30,
        },
        {
            shape: 'box',
            width: 4,
            length: 10,
            height: 0.2,
            position_y: -0.1,
            position_x: 37,
        },
        {
            shape: 'box',
            width: 10,
            length: 4,
            height: 0.2,
            position_y: -0.1,
            position_z: -37,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'checkpoint',
            dataSet: '',
            radius: 1,
            position_y: 1,
            position_z: -30,
            rotation_y: 180,
        },
    ],
};
