export default [
    {
        type: 'vehicle',
        position_y: 13,
        rotation_y: -90,
    },
    {
        type: 'trigger',
        shape: 'sphere',
        event: 'finish',
        position_x: 1,
        position_y: -2.91,
    },
    {
        shape: 'box',
        width: 15,
        height: 0.1,
        length: 15,
        position_x: 6,
    },
    {
        shape: 'box',
        position_y: 12,
        width: 4,
        height: 0.1,
        length: 2,
        position_x: 2,
    },
    {
        shape: 'box',
        position_y: 11.01,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -3.68,
        rotation_z: 30,
    },
    {
        shape: 'box',
        position_y: 10,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -7.4,
    },
    {
        shape: 'box',
        position_y: 11.01,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -11.1,
        rotation_z: -30,
    },
    {
        shape: 'box',
        position_y: 13.51,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -14.1,
        rotation_z: -50,
    },
    {
        shape: 'box',
        position_y: 18.47,
        width: 4,
        height: 0.1,
        length: 2,
        position_x: -17.36,
        rotation_z: -60,
    },
    {
        shape: 'box',
        position_y: 23.44,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -20.63,
        rotation_z: -50,
    },
    {
        shape: 'box',
        position_y: 26.24,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -23.43,
        rotation_z: -40,
    },
    {
        shape: 'box',
        position_y: 28.19,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -26.81,
        rotation_z: -20,
    },
    {
        shape: 'box',
        position_y: 28.86,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -30.65,
    },
    {
        shape: 'box',
        position_y: 19,
        width: 4,
        height: 0.1,
        length: 2,
        position_x: 19,
        rotation_z: 10,
    },
    {
        shape: 'box',
        position_y: 8.17,
        width: 6,
        height: 0.1,
        length: 6,
        position_x: 10.53,
        position_z: 4,
        rotation_z: -40,
    },
    {
        shape: 'box',
        position_y: 10,
        width: 4,
        height: 4,
        length: 2,
        position_x: 4,
        position_z: 4,
    },
    {
        shape: 'box',
        position_y: 12,
        width: 2,
        height: 0.1,
        length: 2,
        position_x: 4,
        position_z: 8,
    },
];
