export default {
    meta: {
        author: '',
        goals: {
            time: 35e3,
            respawnCount: 0,
        },
    },
    elements: [
        {
            type: 'vehicle',
            position_x: 10,
            position_y: 1,
            position_z: 10,
            rotation_y: 90,
        },
        {
            shape: 'box',
            width: 12,
            height: 0.2,
            length: 10,
            position_x: 8,
            position_z: 10,
        },
        {
            shape: 'triangularPrism',
            width: 4,
            length: 4,
            offset: -2,
            position_x: 8,
            position_y: 1,
            position_z: 7,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'setCameraPosition',
            dataSet: '39,13,-6',
            radius: 3,
            position_x: 13,
            position_y: 1,
            position_z: 10,
        },
        {
            type: 'animated',
            shape: 'box',
            width: 6,
            height: 0.2,
            length: 6,
            position_x: -1,
            position_z: 10,
            dataSet: '{ "movement": { "y": -17 }, "alternateDelay": 3, "triggerStart": true }',
        },
        {
            shape: 'box',
            width: 1,
            height: 18,
            length: 0.2,
            position_x: -3,
            position_y: -8.1,
            position_z: 6.9,
        },
        {
            shape: 'box',
            width: 1,
            height: 18,
            length: 0.2,
            position_x: 1,
            position_y: -8.1,
            position_z: 6.9,
        },
        {
            shape: 'box',
            width: 1,
            height: 18,
            length: 0.2,
            position_x: 1,
            position_y: -8.1,
            position_z: 13.1,
        },
        {
            shape: 'box',
            width: 1,
            height: 18,
            length: 0.2,
            position_x: -3,
            position_y: -8.1,
            position_z: 13.1,
        },
        {
            shape: 'box',
            width: 0.2,
            height: 18,
            length: 0.6,
            position_x: -4.1,
            position_y: -8.1,
            position_z: 12,
        },
        {
            shape: 'box',
            width: 0.2,
            height: 18,
            length: 0.6,
            position_x: -4.1,
            position_y: -8.1,
            position_z: 8,
        },
        {
            shape: 'box',
            width: 12,
            height: 0.2,
            length: 10,
            position_x: 8,
            position_z: 10,
            position_y: -17,
        },
        {
            shape: 'box',
            width: 0.2,
            height: 14,
            length: 6,
            position_x: 2.1,
            position_y: -7.1,
            position_z: 10,
            color: 0xc4c4c4,
        },
        {
            shape: 'box',
            width: 12,
            height: 0.2,
            length: 10,
            position_x: 8,
            position_z: 21,
        },
        {
            shape: 'box',
            width: 4,
            height: 10,
            length: 0.6,
            position_x: 8,
            position_z: 15.5,
            position_y: -1,
            mass: 40,
            lowFriction: true,
            fixedRotation: true,
        },
        {
            shape: 'box',
            width: 4,
            height: 14,
            length: 1,
            position_x: 4,
            position_z: 15.5,
            position_y: -3,
        },
        {
            shape: 'box',
            width: 4,
            height: 14,
            length: 1,
            position_x: 12,
            position_z: 15.5,
            position_y: -3,
        },
        {
            shape: 'box',
            width: 1,
            height: 1,
            length: 2,
            position_x: 8,
            position_z: 15.5,
            position_y: -6.5,
            mass: 10,
            lowFriction: true,
            fixedRotation: true,
        },
        {
            shape: 'box',
            width: 2,
            height: 1,
            length: 3,
            position_x: 8,
            position_z: 13.5,
            position_y: -7.5,
        },
        {
            shape: 'box',
            width: 2,
            height: 1,
            length: 2,
            position_x: 8,
            position_z: 17,
            position_y: -7.5,
        },
        {
            shape: 'box',
            width: 2,
            height: 1,
            length: 2,
            position_x: 8,
            position_z: 17,
            position_y: -5.5,
        },
        {
            shape: 'box',
            width: 0.5,
            height: 1,
            length: 2,
            position_x: 7.25,
            position_z: 17,
            position_y: -6.5,
        },
        {
            shape: 'box',
            width: 0.5,
            height: 1,
            length: 2,
            position_x: 8.75,
            position_z: 17,
            position_y: -6.5,
        },
        {
            shape: 'box',
            width: 10,
            height: 0.2,
            length: 8,
            position_x: 9,
            position_z: 9,
            position_y: -8,
        },
        {
            shape: 'box',
            width: 4,
            height: 6,
            length: 0.2,
            position_x: 8,
            position_z: 15.1,
            position_y: -3,
        },
        {
            shape: 'box',
            width: 4,
            height: 6,
            length: 0.2,
            position_x: 8,
            position_z: 15.9,
            position_y: -3,
        },
        {
            shape: 'box',
            width: 0.5,
            height: 1,
            length: 3,
            position_x: 8.75,
            position_z: 13.5,
            position_y: -6.5,
        },
        {
            shape: 'box',
            width: 0.5,
            height: 1,
            length: 3,
            position_x: 7.25,
            position_z: 13.5,
            position_y: -6.5,
        },
        {
            shape: 'box',
            width: 5,
            height: 2,
            length: 1,
            position_x: 4.5,
            position_z: 15.5,
            position_y: -11,
        },
        {
            shape: 'box',
            width: 5,
            height: 2,
            length: 1,
            position_x: 11.5,
            position_z: 15.5,
            position_y: -11,
        },
        {
            shape: 'box',
            width: 12,
            height: 5,
            length: 1,
            position_x: 8,
            position_z: 15.5,
            position_y: -14.5,
        },
        {
            shape: 'sphere',
            radius: 0.5,
            position_x: 8,
            position_z: 14,
            position_y: -6.5,
            mass: 1,
        },
        {
            shape: 'box',
            width: 2,
            height: 1,
            length: 3,
            position_x: 8,
            position_y: -5.5,
            position_z: 13.5,
        },
        {
            shape: 'box',
            width: 1,
            height: 1,
            length: 3,
            position_x: 8,
            position_z: 11.75,
            position_y: -6.5,
            mass: 10,
            fixedRotation: true,
        },
        {
            shape: 'box',
            width: 4,
            height: 0.2,
            length: 4,
            position_x: 16,
            position_z: 7,
            position_y: -17,
        },
        {
            shape: 'box',
            width: 8,
            height: 0.2,
            length: 4,
            position_x: 18,
            position_z: 7,
            position_y: -8,
        },
        {
            shape: 'box',
            width: 4,
            height: 0.2,
            length: 26,
            position_x: 20,
            position_z: 21.75,
            position_y: -10.25,
            rotation_x: 10,
        },
        {
            shape: 'box',
            width: 4,
            height: 0.2,
            length: 26,
            position_x: 16,
            position_z: 21.6,
            position_y: -14.75,
            rotation_x: -10,
        },
        {
            shape: 'box',
            width: 8,
            height: 0.2,
            length: 4,
            position_x: 18,
            position_z: 36.35,
            position_y: -12.5,
        },
        {
            shape: 'box',
            width: 4,
            height: 0.2,
            length: 26,
            position_x: 16,
            position_z: 21.6,
            position_y: -5.76,
            rotation_x: -10,
        },
        {
            shape: 'box',
            width: 4,
            height: 0.2,
            length: 4,
            position_x: 16,
            position_z: 36.35,
            position_y: -3.5,
        },
        {
            shape: 'box',
            width: 2,
            height: 3,
            length: 1,
            position_x: 8,
            position_y: -6.5,
            position_z: 18.5,
        },
        {
            shape: 'box',
            width: 4,
            height: 0.2,
            length: 4,
            position_x: 4,
            position_z: 36.35,
            position_y: -2,
        },
        {
            shape: 'box',
            width: 4,
            height: 0.2,
            length: 8.8,
            position_x: 4,
            position_z: 30.2,
            position_y: -1,
            rotation_x: 13.4,
        },
        {
            shape: 'box',
            width: 8.2,
            height: 0.2,
            length: 4,
            position_x: 10,
            position_z: 36.35,
            position_y: -2.75,
            rotation_z: -10.5,
        },
        {
            shape: 'box',
            width: 0.2,
            height: 4,
            length: 0.2,
            position_x: 6.1,
            position_z: 15.1,
            position_y: 2,
        },
        {
            shape: 'box',
            width: 0.2,
            height: 4,
            length: 0.2,
            position_x: 9.9,
            position_z: 15.1,
            position_y: 2,
        },
        {
            shape: 'box',
            width: 0.2,
            height: 4,
            length: 0.2,
            position_x: 9.9,
            position_z: 15.9,
            position_y: 2,
        },
        {
            shape: 'box',
            width: 0.2,
            height: 4,
            length: 0.2,
            position_x: 6.1,
            position_z: 15.9,
            position_y: 2,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'setCameraPosition',
            dataSet: '-13,4,1',
            radius: 3,
            position_x: -1,
            position_y: 1,
            position_z: 10,
        },
        {
            shape: 'box',
            width: 4,
            height: 0.2,
            length: 12,
            position_x: 8,
            position_z: -17,
            position_y: 2,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'finish',
            dataSet: 'checkpointCount:1',
            position_x: 8,
            position_y: 3,
            position_z: -21,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'setCameraPosition',
            dataSet: '-21,-9,8',
            radius: 3,
            position_x: -1,
            position_y: -9,
            position_z: 10,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'setCameraPosition',
            dataSet: '19,-10,-11',
            radius: 3,
            position_x: 6,
            position_y: -16,
            position_z: 10,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'setCameraPosition',
            dataSet: '30,-3,52',
            radius: 3,
            position_x: 16,
            position_y: -13,
            position_z: 23,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'setCameraPosition',
            dataSet: '43,2,0',
            radius: 3,
            position_x: 16,
            position_y: -14,
            position_z: 17,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'setCameraPosition',
            dataSet: '32,8,-11',
            radius: 3,
            position_x: 20,
            position_y: -9,
            position_z: 20,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'setCameraPosition',
            dataSet: '27,7,43',
            radius: 3,
            position_x: 16,
            position_y: -4,
            position_z: 26,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'setCameraPosition',
            dataSet: '8,12,52',
            radius: 3,
            position_x: 9,
            position_y: -2,
            position_z: 36,
        },
        {
            shape: 'box',
            width: 0.2,
            height: 0.4,
            length: 1.9,
            position_y: 1.1,
            position_z: 11.35,
            position_x: -4.1,
        },
        {
            shape: 'box',
            width: 0.8,
            height: 0.2,
            length: 0.8,
            position_y: 1.4,
            position_z: 10,
            position_x: -4.4,
        },
        {
            shape: 'box',
            width: 0.6,
            height: 0.4,
            length: 0.2,
            position_y: 1.1,
            position_z: 10.3,
            position_x: -4.3,
        },
        {
            shape: 'box',
            width: 0.6,
            height: 0.4,
            length: 0.2,
            position_y: 1.1,
            position_z: 9.7,
            position_x: -4.3,
        },
        {
            shape: 'box',
            width: 0.8,
            height: 0.2,
            length: 0.8,
            position_y: 0.8,
            position_z: 10,
            position_x: -4.4,
        },
        {
            shape: 'box',
            width: 0.2,
            height: 0.4,
            length: 0.8,
            position_y: 1.1,
            position_z: 10,
            position_x: -4.7,
        },
        {
            shape: 'box',
            width: 0.6,
            height: 0.4,
            length: 0.4,
            position_y: 1.1,
            position_z: 10,
            position_x: -4.1,
            mass: 10,
        },
        {
            shape: 'box',
            width: 0.2,
            height: 0.4,
            length: 0.4,
            position_y: 1.1,
            position_z: 10,
            position_x: -3.9,
            type: 'trigger',
            event: 'startAnimation',
            dataSet: 'animated_3',
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'checkpoint',
            position_x: 10.75,
            position_y: -7,
            position_z: 7.5,
            rotation_y: -90,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'setCameraPosition',
            dataSet: '32,8,-11',
            radius: 3,
            position_x: 14.09,
            position_y: -7,
            position_z: 10.04,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'setCameraPosition',
            dataSet: '38,15,11',
            radius: 3,
            position_x: 8,
            position_y: 3,
            position_z: 1,
        },
    ],
};
