export default {
    meta: {
        author: '',
        goals: {
            time: 30_000,
            respawnCount: 0,
        },
        next: 'o01',
    },
    elements: [
        {
            type: 'vehicle',
            position_y: 1,
            position_z: 8,
        },
        {
            shape: 'box',
            width: 22,
            length: 32,
            height: 0.2,
            position_y: -0.1,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'finish',
            dataSet: '',
            radius: 1,
            position_x: -8,
            position_y: 5,
            position_z: 0,
        },
        {
            shape: 'box',
            width: 6,
            height: 4,
            length: 5,
            position_x: 0,
            position_y: 2,
            position_z: 0.5,
            color: '#95c0e5',
            fixedRotation: true,
            mass: 20,
        },
        {
            shape: 'box',
            width: 8,
            height: 4,
            length: 5,
            position_x: -7,
            position_y: 2,
            position_z: 0.5,
            lowFriction: true,
        },
        {
            shape: 'box',
            width: 8,
            height: 4,
            length: 5,
            position_x: 7,
            position_y: 2,
            position_z: 0.5,
            lowFriction: true,
        },
        {
            shape: 'box',
            width: 5,
            height: 2,
            length: 14,
            position_x: 8.5,
            position_y: 1,
            position_z: -9,
        },
        {
            shape: 'triangularPrism',
            position_x: 8.5,
            position_y: 3,
            position_z: -5,
            offset: 3,
            height: 2,
            width: 5,
            length: 6,
        },
        {
            shape: 'triangularPrism',
            position_x: 4,
            position_y: 1,
            position_z: -13.5,
            rotation_y: 90,
            offset: 2,
            height: 2,
            width: 5,
            length: 4,
        },
        {
            shape: 'box',
            position_x: 3.1,
            position_y: 3.9,
            position_z: -6.5,
            length: 9,
            width: 0.2,
            height: 0.2,
            color: '#757575',
            lowFriction: true,
        },
        {
            shape: 'box',
            position_x: -3.1,
            position_y: 3.9,
            position_z: -6.5,
            length: 9,
            width: 0.2,
            height: 0.2,
            color: '#757575',
            lowFriction: true,
        },
        {
            shape: 'box',
            position_x: 0,
            position_y: 3.9,
            position_z: -10.9,
            length: 0.2,
            width: 6,
            height: 0.2,
            color: '#757575',
            lowFriction: true,
        },
        {
            shape: 'box',
            height: 1,
            width: 60,
            length: 60,
            position_x: 0,
            position_y: -2,
            position_z: -2,
            type: 'trigger',
            event: 'reset',
        },
    ],
};
