export default {
    meta: {
        author: '',
        goals: {
            time: 45e3,
            // time: 27e3,
        },
    },
    elements: [
        {
            type: 'vehicle',
            position_x: 0,
            position_y: 1.6,
            position_z: -4,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'finish',
            dataSet: '',
            radius: 1,
            position_x: -16,
            position_y: 5.5,
            position_z: -10,
        },
        {
            shape: 'box',
            color: 0xaad0ff,
            fixedRotation: true,
            width: 5,
            height: 3.79,
            length: 5,
            position_x: -10,
            position_y: -1,
            position_z: -10,
            mass: 90,
        },
        {
            shape: 'box',
            color: 0xaad0ff,
            fixedRotation: true,
            width: 5,
            height: 0.17,
            length: 5,
            position_x: 10,
            position_y: 0,
            position_z: -10,
            mass: 30,
        },
        {
            shape: 'box',
            position_x: -0.4,
            position_y: -1.76,
            position_z: -10.07,
            height: 0.2,
            length: 1,
            width: 24.9,
            color: 0x959dff,
            mass: 30,
        },
        {
            shape: 'triangularPrism',
            position_x: 0,
            position_y: -2.6,
            position_z: -10,
            rotation_y: 90,
            height: 1,
            width: 1,
            length: 1,
        },
        {
            shape: 'box',
            lowFriction: true,
            position_x: -7.45,
            position_y: 0,
            position_z: -10,
            height: 1,
            length: 5,
            width: 0.1,
        },
        {
            shape: 'box',
            lowFriction: true,
            position_x: 7.45,
            position_y: 0,
            position_z: -10,
            height: 1,
            length: 5,
            width: 0.1,
        },
        {
            shape: 'box',
            lowFriction: true,
            position_x: 12.55,
            position_y: -2,
            position_z: -10,
            height: 5,
            length: 5,
            width: 0.1,
        },
        {
            shape: 'box',
            lowFriction: true,
            position_x: -12.55,
            position_y: -2,
            position_z: -10,
            height: 5,
            length: 5,
            width: 0.1,
        },
        {
            shape: 'box',
            lowFriction: true,
            position_x: 10,
            position_y: -2,
            position_z: -7.45,
            height: 5,
            length: 0.1,
            width: 5.2,
        },
        {
            shape: 'box',
            lowFriction: true,
            position_x: 10,
            position_y: -2,
            position_z: -12.55,
            height: 5,
            length: 0.1,
            width: 5.2,
        },
        {
            shape: 'box',
            lowFriction: true,
            position_x: -10,
            position_y: -2,
            position_z: -12.55,
            height: 5,
            length: 0.1,
            width: 5.2,
        },
        {
            shape: 'box',
            lowFriction: true,
            position_x: -10,
            position_y: -2,
            position_z: -7.45,
            height: 5,
            length: 0.1,
            width: 5.2,
        },
        {
            shape: 'box',
            height: 0.2,
            position_x: 0,
            position_y: 0.4,
            position_z: -10,
            width: 14.8,
            length: 5.2,
        },
        {
            shape: 'box',
            lowFriction: true,
            position_x: -7.45,
            position_y: -2.5,
            position_z: -8.5,
            height: 4,
            length: 2,
            width: 0.1,
        },
        {
            shape: 'box',
            lowFriction: true,
            position_x: -7.45,
            position_y: -2.5,
            position_z: -11.5,
            height: 4,
            length: 2,
            width: 0.1,
        },
        {
            shape: 'box',
            lowFriction: true,
            position_x: 7.45,
            position_y: -2.5,
            position_z: -11.5,
            height: 4,
            length: 2,
            width: 0.1,
        },
        {
            shape: 'box',
            lowFriction: true,
            position_x: 7.45,
            position_y: -2.5,
            position_z: -8.5,
            height: 4,
            length: 2,
            width: 0.1,
        },
        {
            shape: 'box',
            height: 0.2,
            position_x: 0,
            position_y: 0.4,
            position_z: -4,
            width: 25.2,
            length: 6.8,
        },
        {
            shape: 'box',
            position_x: -15.08,
            position_y: 4.04,
            position_z: -10,
            length: 5,
            width: 5,
            height: 0.2,
        },
        {
            shape: 'triangularPrism',
            height: 0.1,
            length: 0.2,
            width: 5.5,
            position_x: 10.25,
            position_y: 0.55,
            position_z: -7.5,
        },
        {
            shape: 'triangularPrism',
            height: 0.1,
            length: 0.2,
            width: 5.5,
            position_x: 7.5,
            position_y: 0.55,
            position_z: -10.25,
            rotation_y: 90,
        },
        {
            shape: 'triangularPrism',
            height: 0.24,
            length: 1,
            width: 12,
            position_x: 13,
            position_y: 0.62,
            position_z: -7,
            rotation_y: 90,
        },
        {
            shape: 'triangularPrism',
            height: 0.24,
            length: 1,
            width: 27,
            position_x: 0,
            position_y: 0.62,
            position_z: -13.01,
        },
        {
            shape: 'triangularPrism',
            height: 0.24,
            length: 1,
            width: 12,
            position_x: -13.01,
            position_y: 0.62,
            position_z: -7,
            rotation_y: 90,
        },
        {
            shape: 'box',
            lowFriction: true,
            position_x: -12.55,
            position_y: 4.04,
            position_z: -10,
            height: 0.2,
            length: 5,
            width: 0.1,
        },
        {
            shape: 'triangularPrism',
            height: 0.24,
            length: 1,
            width: 27,
            position_x: 0,
            position_y: 0.62,
            position_z: -1,
        },
        {
            shape: 'box',
            width: 27,
            position_x: 0,
            position_y: -1,
            position_z: -1,
            length: 1,
            height: 3,
        },
        {
            shape: 'box',
            height: 0.2,
            position_x: -16,
            position_y: 0.4,
            position_z: -7,
            width: 5,
            length: 13,
        },
        {
            shape: 'sphere',
            color: 0x77a7ff,
            position_x: 6.25,
            position_y: 1.5,
            position_z: -10,
            mass: 60,
        },
        {
            shape: 'sphere',
            color: 0x77a7ff,
            position_x: -5.36,
            position_y: 1.5,
            position_z: -10,
            mass: 60,
        },
        {
            shape: 'box',
            type: 'trigger',
            event: 'setCameraMode',
            dataSet: 'cinematic,0, 13, 17',
            width: 1,
            length: 10,
            height: 1,
            position_x: 0,
            position_y: 2,
            position_z: -7,
        },
        {
            shape: 'box',
            type: 'trigger',
            dataSet: '-22, 10, 5',
            width: 1,
            length: 10,
            height: 1,
            position_x: -5,
            position_y: 2,
            position_z: -7,
        },
        {
            shape: 'box',
            type: 'trigger',
            dataSet: '8, 14, 6',
            width: 1,
            length: 10,
            height: 1,
            position_x: 5,
            position_y: 2,
            position_z: -7,
        },
    ],
};
