export default {
    vehicle_0: {
        position_x: 10,
        position_y: 1,
        position_z: 10,
        rotation_y: 90,
    },
    box_0: {
        width: 15,
        height: 0.1,
        length: 15,
        position_x: 6,
    },
    box_1: {
        width: 2,
        height: 0.1,
        length: 3,
        position_x: -3,
        position_y: 10,
        position_z: -18,
    },
    box_2: {
        width: 2,
        height: 0.1,
        length: 15,
        position_x: -3,
        position_y: 5,
        position_z: -25,
        rotation_x: 15,
    },
    ramp_3: {
        width: 2,
        length: 2,
        position_x: -5,
        position_y: 0.1,
        position_z: -5,
    },
    ramp_4: {
        width: 2,
        length: 2,
        height: 2,
        position_x: -5,
        position_y: 2.1,
        position_z: -9,
    },
    box_5: {
        width: 2,
        height: 2.7,
        length: 1,
        position_x: -7,
        position_y: 2.6,
        position_z: -9,
    },
    box_6: {
        width: 2,
        height: 5.9,
        length: 1,
        position_x: 1,
        position_y: 5.9,
        position_z: -9,
    },
    box_7: {
        mass: 40,
        position_x: 11,
        position_y: 3,
        position_z: -6,
        width: 2,
        height: 2,
        length: 2,
    },
    cylinder_8: {
        sides: 4,
        radiusBottom: 13,
        height: 0.5,
        position_x: 9,
        position_y: 0.6,
        position_z: -4,
        rotation_y: 45,
        radiusTop: 10,
    },
    cylinder_9: {
        radiusTop: 2,
        radiusBottom: 2,
        height: 2,
        mass: 20,
        sides: 20,
        position_x: -3,
        position_y: 15,
        position_z: -27,
        rotation_z: 90,
    },
    box_10: {
        width: 0.1,
        height: 0.5,
        length: 5,
        position_x: -5.2,
        position_y: 11.3,
        position_z: -33,
        rotation_z: 6,
    },
    box_11: {
        width: 0.1,
        height: 0.5,
        length: 7,
        position_x: -0.85,
        position_y: 11.3,
        position_z: -31,
        rotation_z: -6,
    },
    box_12: {
        width: 0.1,
        height: 0.5,
        length: 15,
        position_x: -0.85,
        position_y: 5.5,
        position_z: -25,
        rotation_x: 15,
        rotation_z: -6,
    },
    box_13: {
        width: 0.1,
        height: 0.5,
        length: 15,
        position_x: -5.15,
        position_y: 5.5,
        position_z: -25,
        rotation_x: 15,
        rotation_z: 6,
    },
    box_14: {
        width: 0.1,
        height: 1,
        length: 0.5,
        position_x: -0.85,
        position_y: 4,
        position_z: -13,
        rotation_y: -6,
    },
    box_15: {
        width: 0.1,
        height: 1,
        length: 0.5,
        position_x: -5.15,
        position_y: 4,
        position_z: -13,
        rotation_y: 6,
    },
    box_16: {
        width: 4.1,
        height: 0.1,
        length: 2,
        position_x: -8.92,
        position_y: 9.65,
        position_z: -26,
        rotation_z: 14.8,
    },
    box_17: {
        width: 2,
        height: 0.1,
        length: 1.2,
        position_x: -7,
        position_y: 5.2,
        position_z: -11.2,
    },
    box_18: {
        width: 2,
        height: 0.1,
        length: 2.2,
        position_x: -10.95,
        position_y: 5.55,
        position_z: -10.2,
        rotation_z: -10,
    },
    box_19: {
        width: 2,
        height: 0.1,
        length: 2,
        position_x: -14.9,
        position_y: 5.9,
        position_z: -10,
    },
    box_20: {
        width: 2,
        height: 0.1,
        length: 6.2,
        position_x: -14.9,
        position_y: 7.25,
        position_z: -17.98,
        rotation_x: 12.55,
    },
    box_21: {
        width: 2.05,
        height: 0.1,
        length: 2,
        position_x: -14.85,
        position_y: 8.6,
        position_z: -26,
    },
    box_22: {
        width: 2,
        height: 0.1,
        length: 1.2,
        position_x: 1,
        position_y: 5.2,
        position_z: -11.2,
    },
    ramp_23: {
        width: 3.3,
        length: 2,
        height: 1,
        position_x: -5,
        position_y: 5.3,
        position_z: -8,
        rotation_y: 270,
        rotation_z: 90,
    },
    box_24: {
        width: 2,
        height: 0.1,
        length: 1.65,
        position_x: -3,
        position_y: 10.35,
        position_z: -22.33,
        rotation_x: 12.5,
    },
    box_25: {
        width: 2,
        height: 0.1,
        length: 2.5,
        position_x: -3,
        position_y: 10.7,
        position_z: -26.4,
    },
    box_26: {
        width: 0.1,
        height: 1,
        length: 7,
        position_x: -0.9,
        position_y: 10.8,
        position_z: -17,
    },
    box_27: {
        width: 2,
        height: 0.1,
        length: 2.2,
        position_x: 5,
        position_y: 5.2,
        position_z: -10.2,
    },
    box_28: {
        width: 2,
        height: 2,
        length: 2,
        position_x: 5,
        position_y: 3.1,
        position_z: -2,
    },
    box_29: {
        width: 2,
        height: 0.1,
        length: 0.1,
        position_x: 9,
        position_z: -3.9,
        position_y: 1.2,
    },
    box_30: {
        width: 4,
        height: 0.1,
        length: 0.1,
        position_x: 7,
        position_z: -8.1,
        position_y: 1.2,
    },
    box_31: {
        width: 0.1,
        height: 0.1,
        length: 2,
        position_x: 2.9,
        position_z: -6,
        position_y: 1.2,
    },
    trigger_32: {
        event: 'setCameraPosition',
        dataSet: '34,11,4.5',
        size: 7,
        position_x: 14,
        position_y: 1,
    },
    trigger_33: {
        event: 'setCameraPosition',
        dataSet: '-3,9,29',
        size: 7,
        position_x: -2,
        position_y: 1,
        position_z: 8,
    },
    trigger_34: {
        event: 'setCameraPosition',
        dataSet: '-30,16,-3',
        size: 3,
        position_x: -3,
        position_y: 12,
        position_z: -21,
    },
    trigger_35: {
        event: 'setCameraPosition',
        dataSet: '-30,22,-29',
        size: 3,
        position_x: -15,
        position_y: 9,
        position_z: -20,
    },
    trigger_36: {
        event: 'setCameraPosition',
        dataSet: '-27,14,-13',
        size: 2,
        position_x: -9,
        position_y: 6,
        position_z: -10,
    },
    trigger_37: {
        event: 'setCameraPosition',
        dataSet: '9.5,10,-25',
        size: 2,
        position_x: 1,
        position_y: 6,
        position_z: -11,
    },
    trigger_38: {
        event: 'setCameraPosition',
        dataSet: '25,11,25',
        size: 3,
        position_x: 10,
        position_y: 1,
        position_z: 10,
    },
    trigger_39: {
        event: 'checkpoint',
        dataSet: '-30,22,-29',
        size: 1,
        position_x: -15,
        position_y: 9,
        position_z: -20,
    },
    trigger_40: {
        event: 'finish',
        dataSet: 'checkpoints:1',
        size: 1,
        position_x: 5,
        position_y: 6,
        position_z: -2,
    },
};
