import map01 from './map_01';
import map02 from './map_02';
import map03 from './map_03';
import map04 from './map_04';

export const mapCollection = {
    map01,
    map02,
    map03,
    map04,
    test: [
        {
            type: 'vehicle',
            position_x: 10,
            position_y: 2,
            position_z: 15,
        },
        {
            shape: 'box',
            width: 12,
            height: 0.1,
            length: 20,
            position_x: 14,
            position_z: 22,
        },
        {
            shape: 'box',
            width: 12,
            height: 0.1,
            length: 20,
            position_y: -1,
        },
        {
            shape: 'box',
            size: 1,
            position_x: 15,
            position_y: 2,
            position_z: 10,
            mass: 40,
            fixedRotation: true,
            rotation_x: 45,
            rotation_y: 45,
        },
        {
            shape: 'box',
            size: 1,
            position_x: 20,
            position_y: 5,
            position_z: 10,
            rotation_x: 45,
            rotation_y: 45,
        },
        {
            type: 'compound',
            shape: 'loop',
            segmentPositionOffset: 0.6,
            position_x: 5,
            position_y: 8.2,
            position_z: 4,
            rotation_x: 12,
        },
        {
            type: 'compound',
            shape: 'slopeTransition',
            segmentHeight: 0.5,
            position_x: 10,
            position_z: -2,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'setCameraPosition',
            dataSet: '-6,10,26',
            size: 3,
            position_x: 10,
            position_y: 1,
            position_z: 15,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'finish',
            size: 1,
            position_x: 12,
            position_y: 3,
            position_z: 5,
        },
        {
            type: 'trigger',
            shape: 'sphere',
            event: 'setCameraMode',
            dataSet: 'hood',
            size: 3,
            position_x: 6,
            position_y: 1,
            position_z: 6.5,
        },
    ],
};
